spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: http://localhost:3000,http://localhost:5173

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
